### ISSUE TITLE
how to solve grgsm_livemon.py

### ISSUE THREAD

**Issue by ayao999** [ptrkrysik/gr-gsm#605]
sudo grcc grgsm_livemon.grc

grgsm_livemon.grc:1:1:FATAL:PARSER:ERR_DOCUMENT_EMPTY: Start tag expected, '<' not found
Error during file compilation

**Comment by velichkov** [comment]
Hi @ayao999,

Which Linux distribution do you use and which version? How did you install gnuradio and gr-gsm, which versions? Why are you building grgsm_livemon.grc manually and why with `sudo`?

**Comment by ayao999** [comment]
I am referring to this article https://osmocom.org/projects/gr-gsm/wiki/Installation's Installation from packages on Debian Testing and Ubuntu 18.04+

**Comment by ayao999** [comment]
I tried to build grgsm_livemon at ubuntu18.04, but couldn't rebuild it, as this article says, as the Article says, As of gr-gsm's version 0.41.2 grgsm_livemon application doesn't work because of change of PyQT version in current Debian Testing and Ubuntu 18.04. In order to use this program you can generate new version out of "grgsm_livemon.grc"

**Comment by ayao999** [comment]
I hope you can understand

**Comment by velichkov** [comment]
> I am referring to this article https://osmocom.org/projects/gr-gsm/wiki/Installation's Installation from packages on Debian Testing and Ubuntu 18.04+

OK, this means you have gnuradio 3.7.11-10 

> I tried to build grgsm_livemon at ubuntu18.04, but couldn't rebuild it, as this article says, as the Article says, As of gr-gsm's version 0.41.2 grgsm_livemon application doesn't work because of change of PyQT version in current Debian Testing and Ubuntu 18.04. In order to use this program you can generate new version out of "grgsm_livemon.grc"

Where did you got grgsm_livemon.grc from? Provide the full output of `head -10 grgsm_livemon.grc`

**Comment by DroidKali** [comment]
Same issue for me.

**Comment by DroidKali** [comment]
> > I am referring to this article https://osmocom.org/projects/gr-gsm/wiki/Installation's Installation from packages on Debian Testing and Ubuntu 18.04+
> 
> OK, this means you have gnuradio 3.7.11-10
> 
> > I tried to build grgsm_livemon at ubuntu18.04, but couldn't rebuild it, as this article says, as the Article says, As of gr-gsm's version 0.41.2 grgsm_livemon application doesn't work because of change of PyQT version in current Debian Testing and Ubuntu 18.04. In order to use this program you can generate new version out of "grgsm_livemon.grc"
> 
> Where did you got grgsm_livemon.grc from? Provide the full output of `head -10 grgsm_livemon.grc`

The grgsm_livemon.grc is from https://gitea.osmocom.org/sdr/gr-gsm/raw/branch/master/apps/grgsm_livemon.grc

The output of `head -10 grgsm_livemon.grc`
```
options:
  parameters:
    author: Piotr Krysik
    category: Custom
    cmake_opt: ''
    comment: ''
    copyright: ''
    description: 'Interactive monitor of a single C0 channel with analysis performed
      by Wireshark (command to run wireshark: sudo wireshark -k -f udp -Y gsmtap -i
      lo)'
    gen_cmake: 'On'
    gen_linking: dynamic
```
